# Mk/Uses/python.mk includes this file, don't remove it!
# $FreeBSD: head/lang/python36/Makefile.version 497138 2019-03-29 14:16:57Z sunpoet $

# Do not forget to update python documentation (lang/python-doc-*)
# Run "make -C lang/python-doc-html makesum"
PYTHON_PORTVERSION=	3.6.8
